basic:
  exp_name: smarts-gaifo
  model_save_dir: /NAS2020/Workspaces/DRLGroup/zbzhu/SMARTS_Imitation/gail_torch/assets/learned_models
  expert_path: /NAS2020/Workspaces/DRLGroup/zbzhu/SMARTS_Imitation/gail_torch/assets/expert_traj/expert.pkl
  tb_log_dir: /NAS2020/Workspaces/DRLGroup/zbzhu/SMARTS_Imitation/gail_torch/assets/tblogs

env_specs:
  env_name: SMARTS-Imitation-v0

exp_params:
  state_only: True
  memory_size: 200000
  update_timestep: 256
  num_updates: 2000
  num_threads: 1

others:
  model_save_freq: 0
